"""add target to assets

Revision ID: 54a2df159fce
Revises: a2f44c8f8111
Create Date: 2026-06-22 12:45:20.649526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54a2df159fce'
down_revision = 'a2f44c8f8111'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'target',
                sa.String(length=255),
                nullable=False,
                server_default=''
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('target')

    # ### end Alembic commands ###
